spring:
  datasource:
    url: jdbc:h2:file:~/gtd-database;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: org.hibernate.dialect.H2Dialect
