spring:
  datasource:
    url: jdbc:oracle:thin:@gtddb_Medium?TNS_ADMIN=/etc/gtd-server/dbwallet
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: gtdapp
    password:
    platform: org.hibernate.dialect.OracleDialect
    hikari:
      schema: gtdapp

logging:
  level:
    com.infosupport: INFO

jwt:
  secret: