spring:
  datasource:
    url: jdbc:oracle:thin:@gtddb_Medium?TNS_ADMIN=/home/ubuntu/dbwallet
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: gtdapp
    password:
    platform: org.hibernate.dialect.OracleDialect
    schema: gtdapp

logging:
  level:
    com.infosupport: INFO

jwt:
  secret: