spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orclpdb1
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: gtdapp
    password:
    platform: org.hibernate.dialect.OracleDialect

jwt:
  secret: